### ISSUE TITLE
Getting errors will not run after initial configuration v2.0

### ISSUE THREAD

**Issue by ew808** [treebeard/BTFGMonitor#1]
![image](https://user-images.githubusercontent.com/27975939/36864698-0690099c-1d53-11e8-9952-987373f857d2.png)

**Comment by nitr8** [comment]
yea, 

1) Does not handle the response from the server well 
2) It's missing the btfgmonitor API key

**Comment by treebeard** [comment]
Won't work without a valid API key, latest commit includes a public api key (not sure if this is still active though).
